### ISSUE TITLE
ICO error

### ISSUE THREAD

**Issue by iegestesi** [halls7588/ERC20-Token-and-ICO-Contract#2]
Ico codes fail. When I paste the byte code instead of creating a contract, it doesn't show me the fee I have to pay. I'm writing a random fee is also the error. this code did not work in any way.

**Comment by halls7588** [comment]
This code does work as it is the same code that was used for 13 different ICO's in 2017, all of which completed successfully. Your complaint has been deemed frivolous as you have not provided any supporting evidence and have failed to read or follow the instructions provided. 

Based on previous frivolous reports and the lack of information provided, it is more then likely that you did not send the required amount of tokens to the ICO smart contract at the time of creation. Just because you do not understand the code, does not mean the code is broken. It's just you.

**Comment by iegestesi** [comment]
I create a contract first. Then I write the byte code that I want to create a contract for ico. Mew doesn't charge me gas. In order to send tokens, an ico contract must be created, right? I do not understand the code I say I have a problem I am doing a due diligence. ico contract doesn't occur so I can send tokens there. I'm telling you it couldn't happen, and you write me a different answer.

**Comment by iegestesi** [comment]
If you look at the photo I sent, I put your current code without changing, but it did not give me the gas fee. I created a normal contract. But I can't create a contract for sale. I'il send a token here if I can.

<a href="https://ibb.co/2y8q48g"><img src="https://i.ibb.co/JKxnJx5/test.jpg" alt="test" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>image hosting</a><br />

**Comment by halls7588** [comment]
This sounds like an error in MEW not in the contract. Here is the GitHub
link to one of the ICOs that used the same code to launch their ICO.
https://github.com/WildCryptoICO/Wild-Crypto-Token
Please make sure you are using the correct version of Solidity and that you
are using the EVM code and ByteCode appropriately

**Comment by iegestesi** [comment]
I'm doing the same version of what the pragma version says. I'm pasting that byte code. Mew also don't know how it could be a mistake.
